site_name: FastAPI RAR to ZIP API 
site_url: https://example.com/
theme: readthedocs

nav:
  - Inicio: index.md
  - Instalación: installation.md
  - Uso: usage.md
  - Referencia de la API: api_reference.md

